<?php
/**
 * @file
 * This module intends to deal with the EU Directive on Privacy and Electronic
 * Communications that comes into effect in the UK on 26th May 2012.
 *
 * Author: Marcin Pajdzik
 */

/**
 * Implements hook_menu().
 */
function eu_cookie_compliance_menu() {
  $items['admin/settings/eu-cookie-compliance'] = array(
    'title' => 'EU Cookie Compliance',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eu_cookie_compliance_admin_form'),
    'access arguments' => array('administer EU Cookie Compliance popup'),
    'file' => 'eu_cookie_compliance.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function eu_cookie_compliance_init() {
  drupal_add_css(drupal_get_path('module', 'eu_cookie_compliance') . '/css/eu_cookie_compliance.css');

  $html_info = str_replace(array("\r", "\n"), '', eu_cookie_compliance_get_popup_content('info'));
  $html_agreed = str_replace(array("\r", "\n"), '', eu_cookie_compliance_get_popup_content('agreed'));
  $height = (int) variable_get('eu_cookie_compliance_popup_height', 200);
  $width = variable_get('eu_cookie_compliance_popup_width', '50%');
  $width = (drupal_substr($width, -1) == '%') ? $width : (int) $width;
  $delay = 1000 * (int) variable_get('eu_cookie_compliance_popup_delay', 1);
  $enabled = variable_get('eu_cookie_compliance_enabled', 0);
  $link = variable_get('eu_cookie_compliance_popup_link', NULL);
  $variables = array(
    'popup_enabled' => $enabled,
    'popup_html_info' => $html_info,
    'popup_html_agreed' => $html_agreed,
    'popup_height' => $height,
    'popup_width' => $width,
    'popup_delay' => $delay,
    'popup_link' => $link,
  );
  drupal_add_js(array('eu_cookie_compliance' => $variables), "setting");
  drupal_add_js(drupal_get_path('module', 'eu_cookie_compliance') . '/js/eu_cookie_compliance.js', 'module', 'footer');
}

/**
 * Implements hook_access().
 */
function eu_cookie_compliance_access() {
  return array('administer EU Cookie Compliance popup');
}

/**
 * Implements hook_theme().
 */
function eu_cookie_compliance_theme() {
  $path = drupal_get_path('module', 'eu_cookie_compliance') . '/theme';
  return array(
    'eu_cookie_compliance_popup_info' => array(
      'template' => 'eu-cookie-compliance-popup-info',
      'arguments' => array('message' => NULL, 'link' => NULL),
      'path' => $path,
    ),
    'eu_cookie_compliance_popup_agreed' => array(
      'template' => 'eu-cookie-compliance-popup-agreed',
      'arguments' => array('message' => NULL, 'link' => NULL),
      'path' => $path,
    ),
  );
}

/**
 * Provides content for EU regulation popups.
 */
function eu_cookie_compliance_get_popup_content($type) {
  $message = filter_xss_admin(variable_get('eu_cookie_compliance_popup_' . $type, ''));
  $link = check_url(variable_get('eu_cookie_compliance_popup_link', ''));
  $output = theme('eu_cookie_compliance_popup_' . $type, $message, $link);
  return $output;
}
